# Generated by Django 4.0 on 2022-01-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='user_name',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='auction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
