# Generated by Django 4.0 on 2022-01-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_user_name_auction_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='categories',
            field=models.CharField(choices=[('Motors', 'Motors'), ('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Collectibles & Art', 'Collectibles & Art'), ('Home & Garden', 'Home & Garden'), ('Sporting Goods', 'Sporting Goods'), ('Toys', 'Toys'), ('Business & Industrial', 'Business & Industrial'), ('Music', 'Music'), ('NONE', 'NONE')], default='NON', max_length=255),
        ),
    ]
