# Generated by Django 4.0 on 2022-01-20 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auction_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='start_price',
            new_name='current_price',
        ),
    ]
